import { type NextPage } from "next";
import Head from "next/head";
import SignIn from "../components/SignIn/Sigin";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Note_App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-bg">
        <SignIn />
      </main>
    </>
  );
};

export default Home;
