import { type NextPage } from "next";
import Head from "next/head";

// Auth
import { useSession } from "next-auth/react";

// Components
import SignIn from "../components/SignIn/Sigin";
import Showcase from "../components/Showcase/Showcase";

const Home: NextPage = () => {
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Note_App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-bg">
        {status === "authenticated" ? <Showcase /> : <SignIn />}
      </main>
    </>
  );
};

export default Home;
