import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Showcase from "../components/Showcase/Showcase";
import SignIn from "../components/SignIn/Sigin";

const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Note_App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-bg">
        {data?.user ? <Showcase /> : <SignIn />}
      </main>
    </>
  );
};

export default Home;
